apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-secret
  namespace: test
type: Opaque
data:
  username:  {{ .Values.username | b64enc | quote }}
  password:  {{ .Values.password | b64enc | quote }}