apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificate.secretName }}
  namespace: test
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls_crt }}
  tls.key: {{ .Values.tls_key }}

  
  